### ISSUE TITLE
Thread for running the OCR

### ISSUE THREAD

**Issue by PrabhakarTayenjam** [adaptech-cz/Tesseract4Android#11]
Does Tesseract4Android runs the OCR on a separate thread other than the UI thread ??
Or the users is responsible for running on separate thread.

What is the right approach to using TessBaseAPI with AsyncTask ??

**Comment by Robyer** [comment]
Tesseract doesn't use special thread, you must handle it yourself.

And please, this isn't issue, you should ask questions like this ("how to use asynctask") on StackOverflow or read some examples.
