### ISSUE TITLE
Cannot interupt OCR process started by getHOCRText

### ISSUE THREAD

**Issue by PrabhakarTayenjam** [adaptech-cz/Tesseract4Android#12]
I use the TessBaseApi inside AsyncTask then call the getHOCRTText using an instance asyncOCR of AsyncOcr as follows :
asyncOcr.execute(image);

In doInBackground method:

 protected String doInBackground(Bitmap... bitmaps) {
            tessAPI.setImage(bitmaps[0]);
            return tessAPI.getHOCRText(0);
  }

When the AsyncOcr is interupted:
@Override
        protected void onCancelled() {
            super.onCancelled();
            tessAPI.stop();
  }

But the OCR is not interupted and runs to completion

Below is the full code of AsyncOcr:

static class AsyncOcr extends AsyncTask<Bitmap, Void, String>{
        private TessBaseAPI tessAPI;
        AsyncOcr(Reader context){
           tessAPI = new TessBaseAPI(new TessBaseAPI.ProgressNotifier() {
                @Override
                public void onProgressValues(TessBaseAPI.ProgressValues progressValues) {
                }
            });
            tessAPI.init(dataPath, model_name, TessBaseAPI.OEM_LSTM_ONLY);
        }
        @Override
        protected void onPreExecute() {
            super.onPreExecute();
            
        }

        @Override
        protected String doInBackground(Bitmap... bitmaps) {
            tessAPI.setImage(bitmaps[0]);
            return tessAPI.getHOCRText(0);
        }
        @Override
        protected void onPostExecute(String text) {
         }

        @Override
        protected void onCancelled() {
            super.onCancelled();
            tessAPI.stop();
        }
    }

**Comment by Robyer** [comment]
You misunderstood how asynctask cancelling works. 

From documentation of `onCancelled()` method: `Runs on the UI thread after cancel(boolean) is invoked and doInBackground(java.lang.Object[]) has finished.`

So you can't stop Tesseract in that method as it is called AFTER the doInBacround() is finished. You need custom method for stopping tesseract. Like this:

```
static class AsyncOcr extends AsyncTask<Bitmap, Void, String>{
	private TessBaseAPI tessAPI;

	AsyncOcr(Reader context){
		tessAPI = new TessBaseAPI(...);
		tessAPI.init(dataPath, model_name, TessBaseAPI.OEM_LSTM_ONLY);
	}

    @Override
    protected String doInBackground(Bitmap... bitmaps) {
        tessAPI.setImage(bitmaps[0]);
        return tessAPI.getHOCRText(0);
    }
	
	public void stopOcr() {
		// Call standard cancel method of the AsyncTask
		cancel();
		
		// Also stop tesseract immediately to interrupt doInBackground()
		tessAPI.stop();
	}
}

// then in code:
asyncOcr.execute(image);
// to cancel use our new method:
asyncOcr.stopOcr();

```

**Comment by PrabhakarTayenjam** [comment]
Thanks. It worked
