### ISSUE TITLE
Not working with some traineddata files for tesseract 4

### ISSUE THREAD

**Issue by nkhdiscovery** [adaptech-cz/Tesseract4Android#13]
Hi guys, great job done! :D 

I used your library for a while and it is working well, until recently that I tried to use with this traineddata file: 
https://github.com/Shreeshrii/tessdata_shreetest/blob/master/fas-minus-float.traineddata

I extracted the mentioned traineeddata file and the .version file says: 
4.0.0-beta.1-232-g45a6:fas:minus20180518:from:4.00.00alpha:Arabic:synth20170629

while for the eng.traineddata shipped with this repo, the .version file says: 
Pre-4.0.0

Is my fas-minus-float.traineddata version is right? Can it be used with your library? 

I soon provide the error thrown on my android device, sorry that I cannot provide it at the moment. Thought maybe the version of my traineddata is not compatible at all so that error is not important.

**Comment by Robyer** [comment]
Hi, I think problem is not in "version" but in the fact that your tessdata uses float model (as they say in repo, and as it is in filename), but models that I link from this repo are integer models. Probably Android requires use of integer models only.

Maybe you will be able to convert that float model into integer model with some `combine_tessdata` script, but I can't help you with that.
