### ISSUE TITLE
Not able to execute gradlew tesseract4android:assembleRelease

### ISSUE THREAD

**Issue by AkankshaEm** [adaptech-cz/Tesseract4Android#14]
Hi,
Thank you for this amazing repository, being new to ocr it took a lot of research to found this repository, which works with tesseract4. I have cloned the project  run the assemblerelease successfully but i am not able to execute gradlew tesseract4android:assembleRelease from terminal.
I tried finding solutions to it which says, 

**Command 'gradlew' not found**

for solving this i am running ,

 gradle wrapper --gradle-version 5.1.1

which is giving the error:

A problem occurred evaluating project ':app'.
> Failed to apply plugin [id 'com.android.application']
 > Minimum supported Gradle version is 5.1.1. Current version is 4.4.1. If using the gradle wrapper, try editing the distributionUrl in /home/akanksha/.gradle/daemon/4.4.1/gradle/wrapper/gradle-wrapper.properties to gradle-5.1.1-all.zip

I have tried updating gradle versions, changing distribution url in gradle wrapper, but not able to execute this, can you please help me with it?

Thank you.

**Comment by Robyer** [comment]
Hi, you are getting `Command 'gradlew' not found`? That means you are just wrongly calling the gradlew script.

Are you on windows? Then you have to be in the project root directory, where you can see the gradlew.bat script.
If you are on linux/mac, it's the same. You must be in the project root directory, but you call `./gradlew` instead of `gradlew.bat` or `gradlew` as you would call on windows.

**Comment by AkankshaEm** [comment]
Yeah it worked perfectly with ./gradlew on linux.

One more thing i needed to know, so i have aar files in my directory, to  use this in my project, i should be creating a new project and import it in libs of my project, is it?
Should i be using debug or release one?

**Comment by Robyer** [comment]
> to use this in my project, i should be creating a new project and import it in libs of my project, is it?
Yes, but you have more options for how to include this library into your project. Compiling AAR manually (or downloading it from Releases tab here) and copying it into your new project and then including that local AAR file in gradle's dependencies block.

Or you can connect this library project itself as module of your main project. That way your project would build this library itself - see here https://medium.com/stantmob/how-to-use-android-libraries-locally-and-leaving-your-development-more-fast-47ef921c6dd9

Or you have few other options, like building library into local maven repository and then importing via classic dependency definition.

> Should i be using debug or release one?
I would just use release build. I think you should use debug build only if your project crashes inside the library for some reason and you want to locate/debug the problem.

**Comment by AkankshaEm** [comment]
Thank you so much for the explanations, all sorted! :)
