### ISSUE TITLE
Jitpack or maven repo

### ISSUE THREAD

**Issue by SubhamTyagi** [adaptech-cz/Tesseract4Android#21]
Thanks for great work,
i used this library in [Trivia Hack(https://github.com/SubhamTyagi/loco-answers) as a  submodule and it working fine. But it will be more helpful for other if you could make available this library as maven (or others types) dependencies for android like [tess-two](https://github.com/rmtheis/tess-two#usage)

Again thanks for this amazing work

**Comment by Robyer** [comment]
@SubhamTyagi Thanks for suggestion. I just released version 4.0.1 and it's now available on JCenter.

**Comment by aguragorn** [comment]
Hi, I get an error when importing the library, I already have jcenter() in my repositories

error:

> Failed to resolve: cz.adaptech.android:tesseract4android:2.0.1

I also can't find the library in [jcenter](https://jcenter.bintray.com/cz/)

**Comment by Robyer** [comment]
@aguragorn Thanks for report. It seems it's only on Bintray - https://dl.bintray.com/adaptech/maven/cz/adaptech/android/tesseract4android/2.0.1/

I'll check what I can do to make it visible on jcenter.

**Comment by Robyer** [comment]
@aguragorn Done. Now it should work.
https://jcenter.bintray.com/cz/adaptech/android/tesseract4android/
