### ISSUE TITLE
How can I use Tess.setVariable(whitelist)?

### ISSUE THREAD

**Issue by owlisie** [adaptech-cz/Tesseract4Android#23]
I tried to use setVariable to use whitelist that I can filter characters.
I heard that Tesseract 4.0 doesn't have whitelist or blacklist but 4.1x does. And this project uses Tesseract 4.1.1.
I made aar file on your guide, copy the aar file on my project's libs folder and implementation on my build.gradle. Is there anything I did wrong way?
If anyone who successfully apply whitelist, PLEASE give me some guide.
Thanks for great works.

**Comment by Robyer** [comment]
Hi @owlisie I just tried the current library version and it works correctly (both whitelist and blacklist). There is test for that, see https://github.com/adaptech-cz/Tesseract4Android/blob/d03bd5fc063d3f34cefd1d48481da38421970136/tesseract4android/src/androidTest/java/com/googlecode/tesseract/android/TessBaseAPITest.java#L681-L703

Maybe you call the setVariable in wrong order?

But also you are talking about aar - you don't need to compile your own aar anymore as I provide maven artifact, so only thing you need to specify dependency in your module's build.gradle dependencies block, like this:

```
dependencies {
    implementation 'cz.adaptech.android:tesseract4android:2.1.0'
}
```

**Comment by owlisie** [comment]
Thanks so much @Robyer !!! I made big mistake that made .aar file and just implement it as ---.aar.
And that .aar maybe was 4.0 version but not that sure.
I've correct dependencies and it works perfect.
Again I sincerely appreciate for your project!
