### ISSUE TITLE
Can not recognize Chinese white texts on black background

### ISSUE THREAD

**Issue by vanhung1710** [adaptech-cz/Tesseract4Android#25]
App can not recognize white Chinese texts on black background. 
These are some samples.
![Screenshot_20200817-105142_MangaToon](https://user-images.githubusercontent.com/5110729/90866294-dfb92b80-e3bd-11ea-9b04-fc19dea2eeb7.jpg)
![Screenshot_20200817-171743_MangaToon](https://user-images.githubusercontent.com/5110729/90866300-e21b8580-e3bd-11ea-91d6-d364997cecbb.jpg)
![Screenshot_20200818-125800_MangaToon](https://user-images.githubusercontent.com/5110729/90866301-e2b41c00-e3bd-11ea-971a-07e2fb7bed0d.jpg)
![Screenshot_20200820-194006_TikTok](https://user-images.githubusercontent.com/5110729/90866302-e34cb280-e3bd-11ea-8798-55f3017bdfe4.jpg)
![Screenshot_20200820-194226_TikTok](https://user-images.githubusercontent.com/5110729/90866307-e3e54900-e3bd-11ea-84ce-7d2e74a36342.jpg)

**Comment by Robyer** [comment]
@vanhung1710 I'm not doing support for Tesseract OCR, this is only wrapper around that library. You need to ask on their official forums if you need help.

I can only recommend doing own preprocessing of the image to have better results. Also you can try to enable parameter:
`mTesseract.setVariable("tessedit_do_invert", "1"); // or "0" to disable it`
This option makes Tesseract try to invert colors automatically to handle white text on black background. I think it's enabled by default, though. You can get some speed gain when you disable it (in case you do your own inverting of that white text).
