### ISSUE TITLE
UnsatisfiedLinkError when trying to create new instance of TessBaseAPI

### ISSUE THREAD

**Issue by spapapan** [adaptech-cz/Tesseract4Android#26]
This is a weird error because it doesn't happen every time - mostly rare - so it's difficult to debug. 
This is the line where the error occurs:

`TessBaseAPI tessBaseApi = new TessBaseAPI();  `  

The error log:

> E/linker: package com.app.myapp: library "/system/lib64/libjpeg.so" ("/system/lib64/libjpeg.so") needed or dlopened by "/system/lib64/libnativeloader.so" is not accessible for the namespace: [name="classloader-namespace", ld_library_paths="", default_library_paths="/data/app/com.app.myapp-4EcKvX8ZmvEUrqVJAF20Dg==/lib/arm64:/data/app/com.app.myapp-4EcKvX8ZmvEUrqVJAF20Dg==/base.apk!/lib/arm64-v8a", permitted_paths="/data:/mnt/expand:/mnt/asec:/data/data/com.app.myapp"]

> D/AndroidRuntime: Shutting down VM
>  E/AndroidRuntime: FATAL EXCEPTION: main
>     Process: com.app.myapp, PID: 6393
>     java.lang.UnsatisfiedLinkError: dlopen failed: library "/system/lib64/libjpeg.so" needed or dlopened by "/system/lib64/libnativeloader.so" is not accessible for the namespace "classloader-namespace"
>         at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
>         at java.lang.System.loadLibrary(System.java:1657)
>         at com.googlecode.tesseract.android.TessBaseAPI.<clinit>(TessBaseAPI.java:52)
>         at com.app.myapp.utils.UtilsOCR.getTessBaseAPI(UtilsOCR.java:257)
>         at com.app.myapp.ocr.OCRTextEvaluator.init(OCRTextEvaluator.java:381)
>         at com.app.myapp.ocr.OCRTextEvaluator.<init>(OCRTextEvaluator.java:48)
>         at com.app.myapp.helper.NotebookWriter.init(NotebookWriter.java:530)
>         at com.app.myapp.helper.NotebookWriter.<init>(NotebookWriter.java:89)
>         at com.app.myapp.exercises.writing.fillblankspen.FillBlanksPenFragment.init(FillBlanksPenFragment.java:382)
>         at com.app.myapp.exercises.writing.fillblankspen.FillBlanksPenFragment.onCreateView(FillBlanksPenFragment.java:77)
>         at androidx.fragment.app.Fragment.performCreateView(Fragment.java:2600)
>         at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:881)
>         at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
>         at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
>         at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
>         at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
>         at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
>         at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
>         at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
>         at androidx.fragment.app.FragmentManagerImpl.dispatchStateChange(FragmentManagerImpl.java:2663)
>         at androidx.fragment.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManagerImpl.java:2613)
>         at androidx.fragment.app.Fragment.performActivityCreated(Fragment.java:2624)
>         at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:904)
>         at androidx.fragment.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManagerImpl.java:1238)
>         at androidx.fragment.app.FragmentManagerImpl.moveToState(FragmentManagerImpl.java:1303)
>         at androidx.fragment.app.BackStackRecord.executeOps(BackStackRecord.java:439)
>         at androidx.fragment.app.FragmentManagerImpl.executeOps(FragmentManagerImpl.java:2079)
>         at androidx.fragment.app.FragmentManagerImpl.executeOpsTogether(FragmentManagerImpl.java:1869)
>         at androidx.fragment.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManagerImpl.java:1824)
>         at androidx.fragment.app.FragmentManagerImpl.execPendingActions(FragmentManagerImpl.java:1727)
>         at androidx.fragment.app.FragmentManagerImpl$2.run(FragmentManagerImpl.java:150)
>         at android.os.Handler.handleCallback(Handler.java:789)
>         at android.os.Handler.dispatchMessage(Handler.java:98)
>         at android.os.Looper.loop(Looper.java:251)
>         at android.app.ActivityThread.main(ActivityThread.java:6572)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)

**Comment by Robyer** [comment]
I've experienced this myself too, but I don't know what is causing it. Maybe bug in linker where in some cases it "forget" to include the compiled libraries into the final package. I think I tried to explicitly link the all cpp libraries in my main project via

```
static {
	System.loadLibrary("jpeg");
	System.loadLibrary("png");
	System.loadLibrary("leptonica");
	System.loadLibrary("tesseract");
}
```

but I don't even remember if it helped or not. If you find some explanation or solution, let me know.

**Comment by matpag** [comment]
Have you ever tried with this: https://github.com/KeepSafe/ReLinker ?
It should fix the problem for minAPI < 23

**Comment by Robyer** [comment]
@matpag Thanks for suggestion, but unfortunately this won't help. This issue happens when the compiled libraries are literally missing in the resulting APK.

**Comment by Robyer** [comment]
@spapapan Please let me know if you still experience this problem with current build tools as I suspect it was just bug in Android Studio / Gradle / ... and not in the library.
