### ISSUE TITLE
Guide for getting it running?

### ISSUE THREAD

**Issue by AxelEriksson0** [adaptech-cz/Tesseract4Android#3]
Hey!

I saw the previous issue for "installed, now what" post but I'm still not able to get it running. Is it possible to get a step-by-step installation walk-through?

**Comment by Robyer** [comment]
Hi, you should be more specific what problem do you have or what do you want to achieve.

For start you can just open this project in Android Studio, open `tesseract4android\src\androidTest\java\com\googlecode\tesseract\android\TessBaseAPITest.java` and then do `Run / Run TessBaseAPITest`. Then if have already copied the tessdata files (eng.traineddata is enough) to your phone's sdcard/tessdata folder, tests should succeed and so you can see there examples of how to use the API.

**Comment by AxelEriksson0** [comment]
My bad! I was just very unfamiliar with adding a dependency you had to build yourself. I got it working now!

Really nice implementation of Tesseract 4.0!! To me, it's more accurate than the 3.04 implementation. However, if speed is a factor, I'd recommend staying on the 3.04 implementation. I ran an image about 10 times and the processing time was:

Tesseract 3.04 - 7.8 seconds.
Tesseract 4.0 Fast - 12 seconds.
Tesseract 4.0 - 28 seconds.

**Comment by Robyer** [comment]
@AxelEriksson0 I see, I will at least provide compiled AAR here when I finish some changes :)

About speed - you don't need to stay on the 3.04 implementation as 4.0 contains the legacy Tesseract engine too. You just have to select it during initialization:

`baseApi.init(TESSBASE_PATH, DEFAULT_LANGUAGE, TessBaseAPI.OEM_TESSERACT_ONLY);`

**Comment by AxelEriksson0** [comment]
Oh, okay! Awesome!

**Comment by softboy99** [comment]
Hi,
How or when it can work with esseract 4.0 Fast tessdata?

**Comment by Robyer** [comment]
@softboy99 You can use Tesseract 4.0 Fast tessdata normally. You can't use legacy tesseract engine with Fast tessdata, only new LSTM engine will work with them.
