### ISSUE TITLE
SegFault in ReadFile.nativeReadBytes8

### ISSUE THREAD

**Issue by fab1ano** [adaptech-cz/Tesseract4Android#32]
Hi,
I encountered a null pointer dereference in `ReadFile.nativeReadBytes8` (`Java_com_googlecode_leptonica_android_ReadFile_nativeReadBytes8`, [here](https://github.com/adaptech-cz/Tesseract4Android/blob/master/tesseract4android/src/main/cpp/leptonica/readfile.cpp#L43)).

Whenever either `pixCreateNoInit` or `pixSetupByteProcessing` return a null pointer, there happens a null pointer dereference at `memcpy` ([here](https://github.com/adaptech-cz/Tesseract4Android/blob/master/tesseract4android/src/main/cpp/leptonica/readfile.cpp#L43)). This can be triggered by causing an Integer overflow in `ReadFile.readBytes8` in the multiplication of the width and height parameter, which leads to `pixCreateNoInit` returning NULL (due to a check in `pixCreateHeader`, called by `pixCreateNoInit`).

In particular, this call gives me a SIGSEGV: 
```
byte[] pixelData = "Some String".getBytes();
Pix p = ReadFile.readBytes8(pixelData, 0x10000, 0x10000);
```

To my knowledge these stubs are originally from Google. Since the google project seems unmaintained and the tess-two project as well is now longer maintained by the author, I think it makes sense to add checks in the wrapper files here.

Pull request #33 adds checks that prevent the crash from happening.

**Comment by Robyer** [comment]
Merged, thanks 🙂
