### ISSUE TITLE
Move to mavenCentral?

### ISSUE THREAD

**Issue by frist008** [adaptech-cz/Tesseract4Android#35]
If you delete jcenter now, then the project is not going to. jcenter is deprecated. Maybe move to mavenCentral?

**Comment by Robyer** [comment]
I will probably move to JitPack for its simplicity.

Actually, you can get the library from JitPack already, just click here: [![](https://jitpack.io/v/adaptech-cz/tesseract4android.svg)](https://jitpack.io/#adaptech-cz/tesseract4android)
