### ISSUE TITLE
Version 4.0.0 not available on Jitpack

### ISSUE THREAD

**Issue by SubhamTyagi** [adaptech-cz/Tesseract4Android#37]
New version(4.0.0) is not available on Jitpack. 
There is error in building this version 
Build logs: https://jitpack.io/com/github/adaptech-cz/tesseract4android/4.0.0/build.log

Old version are available: https://jitpack.io/#adaptech-cz/tesseract4android

**Comment by SubhamTyagi** [comment]
This release built is available here
https://jitpack.io/com/github/adaptech-cz/tesseract4android/7bcebfe632/build.log

So you have re-release new tag(may be new version)

**Comment by Robyer** [comment]
Thanks for the report, I will look into it today.

**Comment by Robyer** [comment]
@SubhamTyagi I started using custom domain name for the JitPack artifact (changed from `com.github.adaptech-cz:*` to `cz.adaptech:*`) few versions ago and I see that the new one (that I use and mention in the docs) is built correctly.

You use this:
https://jitpack.io/#adaptech-cz/tesseract4android

But you should be using this:
https://jitpack.io/#cz.adaptech/tesseract4android

Now I don't really know why JitPack has problem building that `com.github.adaptech-cz` one when it correctly built the `cz.adaptech` one (you can see in logs that it is building from the same commit), but I consider it some JitPack bug. So just update your artifact name and you will be alright.
