### ISSUE TITLE
Couldn't find "libleptonica.so"

### ISSUE THREAD

**Issue by AVTurovskiy** [adaptech-cz/Tesseract4Android#43]
Good afternoon.
I'm trying to link this library to a .jar project. That runs directly without installation. I'm getting the following error on initialization:
"
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/local/tmp/appname.jar"],nativeLibraryDirectories=[/system/lib, /product/lib, /system/lib, /product/lib]]] couldn't find "libleptonica.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
        at java.lang.System.loadLibrary(System.java:1672)
        at com.googlecode.tesseract.android.TessBaseAPI.<clinit>(TessBaseAPI.java:57)
"
Any ideas how to fix this?

**Comment by Robyer** [comment]
@AVTurovskiy This library is intended to be used in Android applications. Are you trying to use it in desktop project (as you are talking about .jar files)?

In any case this question fits more to server like StackOverflow, as it is not specific to this library. Maybe this will help you: https://stackoverflow.com/questions/2937406/how-to-bundle-a-native-library-and-a-jni-library-inside-a-jar

**Comment by AVTurovskiy** [comment]
> @AVTurovskiy This library is intended to be used in Android applications. Are you trying to use it in desktop project (as you are talking about .jar files)?

No. I run it on Android phone. But, withoun installation.

> 
> In any case this question fits more to server like StackOverflow, as it is not specific to this library. Maybe this will help you: https://stackoverflow.com/questions/2937406/how-to-bundle-a-native-library-and-a-jni-library-inside-a-jar

Thanks, I already posted the question there. But he doesn't have the answers yet.
https://stackoverflow.com/questions/72138092/couldnt-find-libleptonica-so-when-start-jar-directly

I agree that this is not a problem with this library. If you don`t have any ideas, as i can make the application see libleptonica.so, we can close this issues.

**Comment by Robyer** [comment]
Interesting, running .jar directly on Android is something new for me.

I commented on your post to suggest that you look into LD_LIBRARY_PATH environmental variable, which could maybe help.
You can also look at these related posts (but I'm not sure if they will be helpful in your case):
- https://stackoverflow.com/questions/8960499/not-able-to-set-ld-library-path-for-java-process/
- https://stackoverflow.com/questions/12873261/ld-library-path-ignored-on-android-sometimes

But even if you solve it, you may end up with problems on some newer versions of Android (starting with Q), where they made stricter rules from what places you can load the .so files. This should be related to that:
- https://stackoverflow.com/questions/63134761/how-to-correctly-find-native-lib-path-in-android

That's all I have, so I'll close the the issue now.
