### ISSUE TITLE
Could not initialize Tesseract API with language

### ISSUE THREAD

**Issue by qinxianyuzou** [adaptech-cz/Tesseract4Android#46]
I used getExternalFilesDir("/testOCR/") on Android12 to obtain external storage, which should not require read and write permissions. I copied the characters in assets to this directory and succeeded, but the Could not initialize Tesseract API with language, not working

**Comment by qinxianyuzou** [comment]
E/Tesseract(native): Could not initialize Tesseract API with language=eng!

**Comment by Robyer** [comment]
@qinxianyuzou Does your `testOCR` directory contains subdirectory called `tessdata` in which are the `*.traineddata` language files? If you have language files directly in `testOCR`, it won't work.

**Comment by qinxianyuzou** [comment]
> 

Yes, with "tessdata" subdirectory and *.traineddata language files

**Comment by Jprillaman** [comment]
I'm having a similar issue, but my program is crashing when I call the utF8Text() function. To my untrained eye, it seems as though the tesseract instance is being created and I loaded up a bitmap image. The application crashes with the same error message as the poster above.

**Comment by Robyer** [comment]
If you can create/share some simple app example where the crash can be reproduced, that would definitely help.

**Comment by Jprillaman** [comment]
> If you can create/share some simple app example where the crash can be reproduced, that would definitely help.

Absolutely, to test the integration of tesseract4android I was using. The image being accessed is a PNG file stored in the drawables folder in resources
`
    val bitmap = BitmapFactory.decodeResource(this.resources, R.drawable.testfile)
    processImage(bitmap)
    
    private fun processImage(bitmap: Bitmap) {
        tess.init(dataPath, "eng")
        tess.setImage(bitmap)
        val text = tess.utF8Text
        Log.d("Tesseract", text)
        if (text != "") {
                Toast.makeText(
                    this@MainActivity,
                    "Calculating...",
                    Toast.LENGTH_SHORT
                 ).show()
                 Log.d("Image_Processor", "text identified")
                 Log.d("Image Processor", text)
                 if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
                           bloomFilterDriver(text)
                 }
          }
          else {
                Toast.makeText(
                      this@MainActivity,
                      "Text not recognized",
                      Toast.LENGTH_SHORT
                )
                      .show()
    }

`

**Comment by Jprillaman** [comment]
Please let me know if you need me to provide more code. This code was housed in my main activity. The top two lines were in a function called onActivityResult which was called after I simulated the use of the camera.

**Comment by Robyer** [comment]
@Jprillaman Just FYI, since Android 10/11, you must handle storage (and storage permissions) differently than before: https://developer.android.com/training/data-storage/use-cases#access-file-paths (yes, internal data folder should always work).
--
I still don't know what @qinxianyuzou's problem might be. I would guess either permissions or some wrong file paths, but it's hard to guess.

**Comment by Jprillaman** [comment]
@Robyer Thank you for the advice. Do you know how I might automate downloading tessdata to my emulated device/physical device? I've just been moving the files around manually, but ideally I would like the application to handle the set up of the tessdata files

**Comment by qinxianyuzou** [comment]
> 我仍然不知道@qinxianyuzou的问题可能是什么。我会猜测权限或一些错误的文件路径，但很难猜测。
I tried it in the demo. There is no redundant code at all. An empty activity just initializes the Tesseract API.
Init code:
``` kotlin
        val path by lazy { getExternalFilesDir("/testOCR/") }
        GlobalScope.launch(Dispatchers.Main) {
            val file = getExternalFilesDir("/testOCR/tessdata/")
            withContext(Dispatchers.IO) {
                file?.let {
                    if (!file.exists()) {
                        file.mkdirs()
                    }
                }
                copyAssetsFile2Local(this@MainActivity, "eng.traineddata")
            }
            tess.init(path?.absolutePath + File.separator, "eng")
        }
```

**Comment by Robyer** [comment]
@qinxianyuzou Have you tried finding the problem with debugger? What is the exception or error and where it occurs in the native code?

**Comment by Robyer** [comment]
I'm closing this as it has been without response for some time, so I expect it has been resolved.

I also verified using both getFilesDir() and getExternalFilesDir() methods in the /sample project on Android 12, and both works correctly there.
