### ISSUE TITLE
Crash on nativeGetUTF8Text

### ISSUE THREAD

**Issue by tomekit** [adaptech-cz/Tesseract4Android#47]
I am getting the whole application to crash, once: `getUTF8Text()` method is called. When used debugger it crashes once I hit the: `nativeGetUTF8Text`. 
Nothing obvious in logs, I can't catch any exception and when I execute the: `tess.utF8Text` line in the debugger I simply get: VMDisconnectedException.

I've tried this dataset: https://github.com/tesseract-ocr/tessdata/blob/4.0.0/eng.traineddata

tried on multiple different images, but no success. Trying on emulator, but on real phone happens as well.

I am using below code.
```
 val assetName = "eng.traineddata"
                    val fileNameOnDevice = "eng.traineddata"
                    val tess = TessBaseAPI()
                    val data: File = File(context.application.dataDir, "tessdata")
                    val traineddataFile = File(data, fileNameOnDevice)
                    if (!traineddataFile.exists()) {
                        data.mkdirs()
                        val src = context.getAssets().open(assetName)
                        FileUtils.copyToFile(src, traineddataFile);
                    }

                    tess.init(context.application.dataDir.absolutePath,"eng")
                    tess.setImage(File(image.absolutePath))
                    try {

                         // CRASHES HERE !
                        val text = tess.utF8Text

                        Toast.makeText(context, text, Toast.LENGTH_SHORT).show()
                    } catch (e : Exception) {
                        val bp = 1
                    }

                    tess.recycle()
```

I am using: 4.1.1 tesseract4android.

Any ideas how to debug what's the issue?

**Comment by tomekit** [comment]
In fact I've missed this in logs: "E/Tesseract(native): Could not initialize Tesseract API with language=eng!" so I think I am going to play around with the placement of traineddata files.

**Comment by tomekit** [comment]
I've actually wasn't getting the file right in this location correctly: `/data/user/0/<appName>/tessdata/eng.traineddata` but when checked in the: `Device File Explorer` that file is there, things started to work properly.

**Comment by Robyer** [comment]
It's good you have found and solved your issue.

For future readers I have updated the example usage in readme to hint that it may be good to check result value of the `tess.init()` before using it for recognition.
