### ISSUE TITLE
mistake in build line

### ISSUE THREAD

**Issue by francoisnicolas** [adaptech-cz/Tesseract4Android#48]
On the github page change :

dependencies {
    // To use Standard variant:
    implementation 'cz.adaptech:tesseract4android:4.1.1'

replace the quote :  implementation "cz.adaptech:tesseract4android:4.1.1"

**Comment by Robyer** [comment]
@francoisnicolas Are you using Kotlin DLS? Because by default Gradle (using Groovy) supports both ' and " for strings, and ' is preferred.
If you are using Kotlin DLS, then changing the quotes is not enough, and you need to also add parentheses around this value.

Or am I missing something?

**Comment by francoisnicolas** [comment]
I use Java and gradle in Android studio (version Arctic fox 2020 3.1) and with simple quote, there is  a fail in compilation.
With double quote, it works

**Comment by Robyer** [comment]
That's strange. Your issue must be somewhere else (maybe when you are copying the text to clipboard, something changes the single quote to some different character). You can see that in my build.gradle files are used single quotes on many places without a problem. So I am closing this as non-issue.
