### ISSUE TITLE
getUTF8Text allways return ""

### ISSUE THREAD

**Issue by softboy99** [adaptech-cz/Tesseract4Android#5]
getUTF8Text allways return ""

**Comment by Robyer** [comment]
Try run the tests in this project. Does they work for you?

**Comment by softboy99** [comment]
yes, i tried with "chi_sim" normal trained, best trained, fast trained data. All of them return ""

**Comment by Robyer** [comment]
So "eng" traineddata works correctly for you, but "chi_sim" doesn't? On what input image do you try that? You can share it here, but I don't think it's problem with the library itself, if english image works correctly.

**Comment by softboy99** [comment]
Hi,
how to give you the image? e-mail? It seems that github cannot attach attachment

**Comment by Robyer** [comment]
You can use for example http://tinypic.com/

But perhaps first try to recognize it with original Tesseract (console application) - https://github.com/tesseract-ocr/tesseract/releases

**Comment by softboy99** [comment]
Hi,
I have upload it.  [ http://tinypic.com/r/5uppua/9](url)

**Comment by Robyer** [comment]
I have no problem with your image.

1) I used https://github.com/tesseract-ocr/tessdata/blob/master/chi_sim.traineddata
2) I copied the image to my phone
3) Then I used this code in tests:
```
final TessBaseAPI baseApi = new TessBaseAPI();
boolean success = baseApi.init(TESSBASE_PATH, "chi_sim", TessBaseAPI.OEM_LSTM_ONLY); // or TessBaseAPI.OEM_TESSERACT_ONLY to use old Tesseract API
assertTrue(success);

final Bitmap bmp = BitmapFactory.decodeFile(Environment.getExternalStorageDirectory().getAbsolutePath() + "/5uppua.jpg");
baseApi.setImage(bmp);

String recognizedText = baseApi.getUTF8Text();
Log.i("TAG", "Result: " + recognizedText);
		
baseApi.end();
bmp.recycle();
```

4) Result using TessBaseAPI.OEM_LSTM_ONLY took about 48 seconds to recognize and is:

```
E c
o E
C C 园
E 1 学 雷 目 八 囡
, 营 业 执 煌 ,
D - 尸 “ 朋 野 东 息 。 | E
口 统 一 社 会 信 用 代 码 914401010878371368 腐
旧
2 名 称 “ 广 州 金 至 检 测 技 术 有 限 公 司 怡
5 类 型 “ 有 限 责 任 公 司 ( 法 人 独 资 ) 区
住 所 “ 广 川 市 海 珠 区 新 港 东 路 2429 号 411 房 ( 仅 作 办 公 用 逍 ) |
月 法 定 代 表 人 享 姬 【
引 注 册 资 本 喜 仗 万 元 整 B
F 成 立 日 期 201402 月 10 日 ]
〖 营 业 期 限 2014402 月 10 日 至 长 期 闵
= 经 营 范 围 专 业 技 术 服 务 业 ( 具 体 经 营 项 目 请 登 录 广 州 ˇ 【-
] 市 商 事 主 体 信 息 公 示 平 台 查 询 。 依 法 须 经 批 ˇ |
Q 准 的 项 目 , 经 相 关 部 门 批 准 后 方 可 开 展 经 营 ˇ |
b 活 动 。 ) 闵
日 em |
挂 尿
,
, 月
刀 河 酉 沙 【
| 脱 4 驼 、 目
国 登 记 机 关 ( 垮 又 踏 | 间
D 医 E
刀 2016 “ 年 R_ 月 057 白 【
C 1 仪 CENEETN 余 8
```
