### ISSUE TITLE
Error with initialize tessdata

### ISSUE THREAD

**Issue by Vanlakhan02** [adaptech-cz/Tesseract4Android#50]
Hey, i have got the error where is say "couldn't initialize tesseract api with language", i have try many solution, even create subdirectory "tessdata". but it isn't work
![Error](https://user-images.githubusercontent.com/100562151/196205277-6886e992-1dc3-46a7-a831-faa10f9f3769.png)

**Comment by Robyer** [comment]
I see you are using some custom "plate" language. I recommend to first try to make it work with standard english language and when it works, start trying custom one.

Depending on Android version where you are trying this app, you may have problem with permissions to access that path, for example. Or the language file used can be incompatible with the LSTM engine and you would need to use the LEGACY engine instead (or vice-versa).

**Comment by Robyer** [comment]
I just created a sample app (see the sample folder) that you can use as a quick test, as it doesn't use external storage.

**Comment by Vanlakhan02** [comment]
thank you so much for your replying. it is really helpful and now my problem have been already solved
