### ISSUE TITLE
Cannot resolve symbol 'TessBaseAPI'

### ISSUE THREAD

**Issue by spapapan** [adaptech-cz/Tesseract4Android#51]
I am trying to switch from:

  ` implementation 'cz.adaptech.android:tesseract4android:2.1.0'`

to:

   `implementation 'cz.adaptech:tesseract4android:4.1.1'`

But when I try to use the class TessBaseAPI I am not able to import it. With the 2.1.0 version I was able to import it with:

 `import com.googlecode.tesseract.android.TessBaseAPI;`

What am I missing here?

**Comment by Robyer** [comment]
There shouldn't be any change in the import statements. I just tried with clean project and it works.

Make sure to check your project's main build.gradle file whether you have correctly listed JitPack in repositories block. As in:
```
allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
}
```

**Comment by Robyer** [comment]
I just created a sample app (see the sample folder) that you can use as a quick test. It uses the 4.1.1 version from JitPack as dependency.

**Comment by spapapan** [comment]
Thanks a lot for your effort.

**Comment by Robyer** [comment]
I expect you have solved your issue, so I'm closing this. If there is still a problem, feel free to reopen this issue or create another one.

**Comment by spapapan** [comment]
Actually I switched to Digital ink with ML Kit. It supports 300 languages, the implementation is super easy, the recognition score is outstanding and it's free! Check it out if you didn't have the chance, they released it last year. 

Thanks again for taking the time to respond to me.

**Comment by Robyer** [comment]
Thanks for tip! I'll check it out 👍
