### ISSUE TITLE
How to get scan progress

### ISSUE THREAD

**Issue by CarlosCMD** [adaptech-cz/Tesseract4Android#57]
How do i get the scan progress to a progress bar or progress dialog(custom).

**Comment by Robyer** [comment]
Check the sample project here: https://github.com/adaptech-cz/Tesseract4Android/tree/master/sample

**Comment by Robyer** [comment]
To be specific:
1) Set listener on constructor:
https://github.com/adaptech-cz/Tesseract4Android/blob/7d6576b6039dc36be397411ad9ffa72813dc8c32/sample/src/main/java/cz/adaptech/tesseract4android/sample/ui/main/MainViewModel.java#L42-L44
2) Call getHOCRText() method to trigger the recognition before you call getUTF8Text() or other method to retrieve the result.
https://github.com/adaptech-cz/Tesseract4Android/blob/7d6576b6039dc36be397411ad9ffa72813dc8c32/sample/src/main/java/cz/adaptech/tesseract4android/sample/ui/main/MainViewModel.java#L101-L111
