### ISSUE TITLE
Size of built libraries is too much

### ISSUE THREAD

**Issue by emandtf** [adaptech-cz/Tesseract4Android#59]
I'm coming from the not-more-maintained "tess-two" project for Tesseract and the resulting ARM7v libraries are very smaller compared to those build from Tesseract4Android.

Tess-two sizes (Release - ARM7v):
- libjpgt.so: 170Kb
- liblept.so: 1.8MB
- libpngt.so: 150Kb
- libtess.so: 2.6MB

Android4Tesseract sizes (Release - ARM7v):
- libjpeg.so: 800Kb
- libleptonica.so: 7.8MB
- libpngx.so: 560Kb
- libtesseract.so: 30MB!!!!!!!

Android4Tesseract sizes (Release - ARM64-8a):
- libjpeg.so: 1MB
- libleptonica.so: 11MB
- libpngx.so: 750Kb
- libtesseract.so: 36MB!!!!!!!

I think something is going wrong here.....

**Comment by Robyer** [comment]
I just downloaded the [tesseract4android-4.4.0.aar](http://jitpack.io/cz/adaptech/tesseract4android/tesseract4android/4.4.0/tesseract4android-4.4.0.aar) directly from JitPack and the sizes are normal. Perhaps you accidentally compiled debug version?

![image](https://github.com/adaptech-cz/Tesseract4Android/assets/359173/8ebb6558-ddd8-4b2a-8db6-a84dc3dd22d8)

**Comment by emandtf** [comment]
Nope because if I create this fake_and_corrupted method inside a "#ifdef DEBUG...#endif" section...

> non_existent_type test { } 

...the compiler doesn't stops building the project.
Instead, if I switch to Debug the compiler stops at that method. 
Debug version is (the sum of all 4 libraries) 10MB bigger, so I'm sure I'm building for Release.

**Comment by Robyer** [comment]
Make sure to set this:

https://github.com/adaptech-cz/Tesseract4Android/blob/66bade85ce2627608c0b91124e267aa9d815f8a0/tesseract4android/build.gradle#L41-L49

**Comment by Robyer** [comment]
@emandtf Have you solved your problem?

**Comment by emandtf** [comment]
> @emandtf Have you solved your problem?

I should added "-s" argument for shrinking which is not present in the maker 🤷‍♂️
