### ISSUE TITLE
How can i import  this project in Android Studio's build.gradle

### ISSUE THREAD

**Issue by DorisGM** [adaptech-cz/Tesseract4Android#6]

**Comment by Robyer** [comment]
This is standard Android Studio library project which you can directly open and compile yourself. Also I provide compiled AAR for direct download (see Releases tab). Currently I don't provide maven artifact if that's what you are asking.

You have different ways how to include this library into your project. Use Google. This is not issue specific for this library. See for example - https://stackoverflow.com/questions/16682847/how-to-manually-include-external-aar-package-using-new-gradle-android-build-syst

**Comment by DorisGM** [comment]
Thanks a lot , by the way,  I'm not familiar familiar with C++. but I  try to compile tesseract 4.0 for Android by myself . Is there have some tutorial about compile ?

**Comment by Robyer** [comment]
You don't need any knowledge about C++. You just open this library project in Android Studio and then  in Gradle panel start the tesseract4android:assembleRelease task. That will result in compiling the same AAR file as you can download here.

If you don't want to use AAR as dependency in your project, you can also set dependency on project itself, see for example: https://medium.com/stantmob/how-to-use-android-libraries-locally-and-leaving-your-development-more-fast-47ef921c6dd9

**Comment by DorisGM** [comment]
Thanks a lot.  And  I compare decode performance by the same picture. The text recognition time than used  Tessaract4Android is same as used tess-two 。
Tessaract 4.0 performance should be better than 3.0.5 , is it right?

**Comment by Robyer** [comment]
> The text recognition time than used Tessaract4Android is same as used tess-two
Perhaps you selected OEM_TESSERACT_ONLY (legacy OCR engine)? Then that would be same, as that is the 3.0 engine.

If you choose OEM_LSTM_ONLY (4.0 engine) then it will depend... It would be more accurate, but slower (at least for latin languages). See https://github.com/tesseract-ocr/tesseract/wiki/4.0-Accuracy-and-Performance

**Comment by DorisGM** [comment]
It's wired. I selected OEM_LSTM_ONLY  and use TrainData with LSTM traindata. It spend more time than tess-two.  Which project you suggested if  I prefer to recognition more fast?

**Comment by DorisGM** [comment]
Yes,  OES_LSTM_ONLY is more accuracy but slower.  And How can i  do 
  ompromise speed and accuracy,  faster and accuracy is not too bad?

**Comment by DorisGM** [comment]
Maybe Because of the 4.0.0  used LSTM ，It is so heavy for Android CPU that need spend more time to recognition.

**Comment by Robyer** [comment]
Yes, LSTM is heavy on Android. On computers they use AVX and other CPU instructions to speed up the algorithm, but on Android it's not available and they haven't used similar ARM instructions, so it's slower.

One possible compromise is to use fast tessdata models (https://github.com/tesseract-ocr/tessdata_fast) which will be faster than LSTM tessdata (but less precise), but still slower than tesseract 3.0 (but more precise).

But for future similar questions/optimizations you should consult original Tesseract forum/repository/developers, I'm not affiliated with their product and I know only what I read there.
