### ISSUE TITLE
Can you please downgrade Java version?

### ISSUE THREAD

**Issue by Vensent** [adaptech-cz/Tesseract4Android#63]
Hi,

I'm using this API in 4.4. As I intend to upgrade to 4.6.0, I got the error that my application's java version does not match java 17. And it fails to build.

So, can you please downgrade this lib to java 8? So many applications can use it without unnecessary java's upgrading.
Thanks.

**Comment by Robyer** [comment]
Btw version 4.5.0 was using Java 11, so your project also compiles with Java 11 already. Switching to Java 17 should have no negative impact for you.
