### ISSUE TITLE
401 Unauthorised when fetching from Jitpack

### ISSUE THREAD

**Issue by britneybcs** [adaptech-cz/Tesseract4Android#70]
> Could not resolve cz.adaptech.android:tesseract4android:2.1.0.
[        ]          > Could not get resource 'https://jitpack.io/cz/adaptech/android/tesseract4android/2.1.0/tesseract4android-2.1.0.pom'.
[        ]             > Could not GET 'https://jitpack.io/cz/adaptech/android/tesseract4android/2.1.0/tesseract4android-2.1.0.pom'. Received status code 401 from server: Unauthorized
[        ]       > Could not resolve cz.adaptech.android:tesseract4android:2.1.0.
[        ]          > Could not get resource 'https://www.jitpack.io/cz/adaptech/android/tesseract4android/2.1.0/tesseract4android-2.1.0.pom'.
[        ]             > Could not GET 'https://www.jitpack.io/cz/adaptech/android/tesseract4android/2.1.0/tesseract4android-2.1.0.pom'. Received status code 401 from server: Unauthorized

**Comment by Robyer** [comment]
I changed the package name from `cz.adaptech.android.tesseract4android` to `cz.adaptech.tesseract4android` around that time, so changing it to https://jitpack.io/cz/adaptech/tesseract4android/2.1.0/ will work.

Btw the version 2.1.0 is very old, current is 4.7.0.
