### ISSUE TITLE
Android15 16KB Page Size Support

### ISSUE THREAD

**Issue by amengchao** [adaptech-cz/Tesseract4Android#71]
I have followed the android15's instructions accordingly. 
google guide :https://developer.android.com/guide/practices/page-sizes?hl=en
However,when executing `new TessBaseAPI();` on the pixel 8(16KB Page Size),my app crashed.
Here is the crash log:
> java.lang.UnsatisfiedLinkError: dlopen failed: "....../lib/arm64/libjpeg.so" program alignment (4096) cannot be smaller than system page size (16384)

It seems that corresponding adjustments need to be made on this SDK side as well. So do you have any plans for this?

**Comment by amengchao** [comment]
@Robyer hey guys,could you help to follow this one?

**Comment by Robyer** [comment]
Hi, thanks for reminder. I'll try to test it tomorrow.

I understand it just needs to update the used SDK and NDK to a newer version and add this parameter to build.gradle:

```
android {
  ...
  defaultConfig {
    ...
    // This block is different from the one you use to link Gradle
    // to your CMake or ndk-build script.
    externalNativeBuild {
      // For ndk-build, instead use the ndkBuild block.
      cmake {
        // Passes optional arguments to CMake.
        arguments "-DANDROID_SUPPORT_FLEXIBLE_PAGE_SIZES=ON"
      }
    }
  }
}
```

then just recompile everything and it should work? Have you tried this or have you missed the build.gradle step?

**Comment by amengchao** [comment]
@Robyer Thanks for response.
I also upgraded the AGP and Gradle version.
AGP:8.6.1
Gradle:8.7

And it worked on my pixel 8(16KB Page Size).

According to the Android15‘s guide, if the AGP is below 8.5,perhaps this code is also needed.
```
android {
  ...
  packagingOptions {
      jniLibs {
        useLegacyPackaging true
      }
  }
}
```
