### ISSUE TITLE
How to set a custom confidence value

### ISSUE THREAD

**Issue by rafinharodrigues** [adaptech-cz/Tesseract4Android#72]
Hello, i'm newbie using Android and i did not found the correct place in the code where i can set a different value for the detection confidence. Could you please show me where can i do this?

**Comment by Robyer** [comment]
Hi, currently you need to use result iterator and filter the words yourself.

Similarly like with this answer: https://stackoverflow.com/a/54992554

But probably iterate over words. And you should be able to get the confidence value for each item.

Let me know in case you need further help.

**Comment by Robyer** [comment]
@rafinharodrigues Using wordConfidences as in your example also works, but using ResultIterator directly would be a bit cleaner way.

I just implemented helper method using the ResultIterator, where you can also filter the result not only by words, but by any iterator level (symbol, word, paragraph, block).

See here. It doesn't use any private method so you can copy it (with small modification) directly to your project or compile Tesseract4Android from source to use it.

https://github.com/adaptech-cz/Tesseract4Android/blob/d433dba9c057a892c46aa37a2798e08270cccf01/tesseract4android/src/main/java/com/googlecode/tesseract/android/TessBaseAPI.java#L719-L792
