### ISSUE TITLE
How to pass ocr configurations properly

### ISSUE THREAD

**Issue by peterbence3** [adaptech-cz/Tesseract4Android#8]
I tried to put my `anpr.tessconfig` configuration file into `/sdcard/tesseract/tessdata `where it contains:
```
load_system_dawg 0
load_freq_dawg 0
tessedit_char_whitelist 0123456789ABGRZSTJPMNO
user_patterns_suffix anpr.user-patterns
```
Knowing that ` anpr.user-patterns `is my pattern file _(holding this pattern only: \c\d\*)_ placed at the same destination, I tried to pass these configs using the `readConfigFile `function as follows, however it seems not to be working, neither for the `setPageSegMode`.

```
mTess = new TessBaseAPI();
 mTess.setPageSegMode(TessBaseAPI.PageSegMode.PSM_SINGLE_WORD);
mTess.readConfigFile("anpr.tessconfig");
mTess.init(datapath, "eng");
```

Please note that i tried to pass the configs using the setVariable() function like this:
```
mTess.setVariable("load_system_dawg", "false");
mTess.setVariable("load_freq_dawg", "false");
mTess.setVariable("tessedit_char_whitelist", "0123456789ABGRZSTJPMNO");
mTess.setVariable("user_patterns_suffix", "anpr.user-patterns");
```
but still not working either.
any help would be highly appreciated. Thanks!!

**Comment by Robyer** [comment]
@peterbence3 I'm not sure what the load_system_dawg and load_freg_dawg does, but char whitelist and user patterns are not supported in the LSTM engine of Tesseract 4.0 yet. You can use LEGACY engine (i.e. the same engine as was in Tesseract 3.x) and there should your config changes work. But for LSTM, you must wait for new version (I saw they implemented the char whitelist in their current development branch).

**Comment by peterbence3** [comment]
@Robyer thanks for your reply. `load_system_dawg `and `load_freg_dawg` enables or disables the load of the dictionaries that tesseract usually uses for grammar matching with results. [There is a great page here](http://www.sk-spell.sk.cx/tesseract-ocr-parameters-in-302-version) that has a list of almost all tesseract configuration keys.

So by returning to your answer, could i use the` init(String datapath, String language, int ocrenginemode) `to pass **TessBaseAPI.OEM_TESSERACT_ONLY** as my ocr engine mode and all of my configs will work?

**Comment by Robyer** [comment]
> could i use theinit(String datapath, String language, int ocrenginemode)to pass TessBaseAPI.OEM_TESSERACT_ONLY as my ocr engine mode and all of my configs will work?
Yes, I expect that would work. 

> Edit: I tried to do that but i got the following error (Could not initialize Tesseract API with language=eng):
Make sure you use correct tessdata. You **can't use _fast/_best version** if you intend to use the LEGACY engine. You must use this https://github.com/tesseract-ocr/tessdata

**Comment by peterbence3** [comment]
thanks this solves the crashing issue, i were using a _fast version. However still struggling to make my configurations have effect. Tried both of reading them from a config file, and passing it through the `setVariable()` function but none worked. Any thoughts?

**Comment by Robyer** [comment]
@peterbence3 See these tests, they are using whitelist/blacklist and if I remember they worked: 

https://github.com/adaptech-cz/Tesseract4Android/blob/master/tesseract4android/src/androidTest/java/com/googlecode/tesseract/android/TessBaseAPITest.java#L632-L704

But I'm not sure how other parameters are implemented in the Tesseract 4.0. Perhaps you can try with their console application and see whether your config/parameters works at least there or not.

**Comment by peterbence3** [comment]
That is great, i realized that i must call the setVariable() function after the init() function, i don't know why is that but it worked!!

**However**, i have an old problem to solve now that is the `user_patterns`. I've tried to set it through the `user_pattern `option as well as the `user_patterns_suffix `configuration, both on windows tesseract java wrapper and this android library and on every available **oem** but it seems that it has no effect at all on the output at all. I'd made sure that tesseract is accessing my user-patterns file, where i get an error message (File Not Found) when i remove it from the tessdata path.

Thanks for your patience <3

**Comment by Robyer** [comment]
Nice. So if the `user_patterns` problem is present even in Tesseract console app then I can't help you here anymore and you would need to search or ask on official Tesseract forum. I have never used that feature :)

**Comment by peterbence3** [comment]
@Robyer, So many thanks!!
