### ISSUE TITLE
Setting language for TessBaseApi gives error

### ISSUE THREAD

**Issue by PrabhakarTayenjam** [adaptech-cz/Tesseract4Android#9]

**Comment by PrabhakarTayenjam** [comment]
When calling TessBaseApi init with
tessBaseAPI.init("app/src/main/res/tessdata/", "ben", TessBaseAPI.OEM_LSTM_ONLY);
I got an error:
app\src\main\res\tessdata\ben.traineddata: Error: The file name must end with .xml

What to do??. I tried making the tessdata directory a android resource directory and putting the traineddata file in there, didn't help.

**Comment by Robyer** [comment]
You need to put the traineddata to sdcard, it can't be loaded directly from the APK.

If you want to distribute it with the app itself, you can for example copy it from APK (from assets) to sdcard if they doesn't exists there yet. Here is related quesiton on stackoverflow how to extract the files from assets to sdcard - https://stackoverflow.com/questions/46109858/how-can-i-read-multiple-data-from-assets

**Comment by PrabhakarTayenjam** [comment]
Thanks @Robyer. I can extract the traineddata files to my android device. But now I cannot initialise TessBaseApi.

Heres my code:
...
    TessBaseAPI tessBaseAPI = new TessBaseAPI();
    final String TESSDATA_PATH = new File(Environment.getExternalStorageDirectory(),
            "/Tess/tessdata/").toString(); // path to tessdata directory on device
    @Override
    protected void onCreate(Bundle savedInstanceState) {
                   super.onCreate(savedInstanceState);
                   setContentView(R.layout.activity_main);
                   String[] permissions = {
                           "android.permission.READ_EXTERNAL_STORAGE",
                           "android.permission.WRITE_EXTERNAL_STORAGE"
                   };
                   requestPermissions(permissions, 10);
                   extractTrainedData(); // extracting traineddata,    SUCCESS
                   tessBaseAPI.init(TESSDATA_PATH, "ben+~eng", TessBaseAPI.OEM_LSTM_ONLY); //error here
    }


Am I missing something before init method??

**Comment by PrabhakarTayenjam** [comment]
I solved it. It was a silly mistake. datapath argument should be the path of the directory containing the tessdata subdirectory not the path of the tessdata directory.  


This can be close now.
Thanks again @Robyer .
